Senzing.Sdk.Tests/core/SzCoreEngineReadTest.cs, Senzing.Sdk/SzEngine.cs, Senzing.Sdk/core/SzCoreEngine.cs
Adds FindInterestingEntities() functions and associated tests.
Resolves Issue #42
=> Adds FindInterestingEntities() functions and associated tests.

.config/dotnet-tools.json, CHANGELOG.md, README.md, Senzing.Sdk/Senzing.Sdk.csproj, Senzing.Sdk/SzConfig.cs, Senzing.Sdk/SzConfigManager.cs, Senzing.Sdk/SzDiagnostic.cs, Senzing.Sdk/SzEngine.cs, Senzing.Sdk/SzFlag.cs, Senzing.Sdk/SzFlagUsageGroup.cs, Senzing.Sdk/SzFlags.cs, Senzing.Sdk/SzProduct.cs, Senzing.Sdk/Utilities.cs, Senzing.Sdk/core/NativeConfig.cs, Senzing.Sdk/core/NativeConfigExtern.cs, Senzing.Sdk/core/NativeConfigManager.cs, Senzing.Sdk/core/NativeConfigManagerExtern.cs, Senzing.Sdk/core/NativeDiagnosticExtern.cs, Senzing.Sdk/core/NativeEngine.cs, Senzing.Sdk/core/NativeEngineExtern.cs, Senzing.Sdk/core/SzCoreConfig.cs, Senzing.Sdk/core/SzCoreConfigManager.cs, Senzing.Sdk/core/SzCoreDiagnostic.cs, Senzing.Sdk/core/SzCoreEngine.cs, Senzing.Sdk/core/SzCoreEnvironment.cs, Senzing.Sdk/core/SzCoreProduct.cs, docfx.json, index.md, toc.yml
- Removed the analyzers as a direct library dependency
- Fixed documentation comment typos and broken links
- Configured documentation generation to `Senzing.Sdk.csproj`
- Added `README.md` content as well as `CHANGELOG.md`
- Added files to support documentation generation
- Changed core implementation classes to be `internal`
=> Final preparation steps for beta release

.github/workflows/create-docfx-documentation.yaml
=> #47 add doc generation github action

CHANGELOG.md, Senzing.Sdk.Tests/nativeszapi/InstallLocations.cs
Added code for to auto-detect `SENZING_DIR` when building as a sub-module of the Senzing product.
=> 0.9.1 release: Added auto-detection of SENZING_DIR if building as a product submodule

.github/workflows/dotnet-darwin.yaml, .github/workflows/dotnet-linux.yaml, .github/workflows/dotnet-windows.yaml
=> update osx and win install

CHANGELOG.md, README.md, Senzing.Sdk/Senzing.Sdk.csproj, Senzing.Sdk/SzFlag.cs, Senzing.Sdk/SzFlagUsageGroup.cs, Senzing.Sdk/SzFlags.cs, Senzing.Sdk/core/NativeFlags.cs
- Changed versioning to match major version of Senzing 4.0 product with beta suffix.
- Made changes to return `null` when INFO is **not** requested.
- Added full 
- Patched `SzCoreEngine.ReevaluateEntity()` to return place-holder `NoInfo` when
INFO requested, but entity not found (pending fix to native engine function).
- Added new engine flags:
- `SzSearchIncludeAllCandidates`
- `SzSearchIncludeRequest`
- `SzSearchIncludeRequestDetails`
- Added full exception hierarchy:
- `SzConfigurationException`
- `SzRetryableException`
- `SzDatabaseConnectionLostException`
- `SzRetryTimeoutExceededException`
- `SzUnrecoverableException`
- `SzDatabaseException`
- `SzLicenseException`
- `SzNotInitializedException`
- `SzUnhandledException`
- Added full error code to exception mapping from …
=> Updates for version 4.0.0-beta.1.1

.github/workflows/create-docfx-documentation.yaml
=> add doc support for beta version tag

CHANGELOG.md, Senzing.Sdk.Tests/SzExceptionTest.cs, Senzing.Sdk/Senzing.Sdk.csproj, Senzing.Sdk/SzDatabaseTransientException.cs, Senzing.Sdk/core/SzExceptionMapper.cs
Resolves Issue #61 
Added SzDatabaseTransientException and mappings to it.
=> Added SzDatabaseTransientException and mappings to it

README.md
Just fixed spelling of "distribution"
=> Update README.md - spelling error

README.md
Updated `README.md` to reflection version `4.0.0-beta.2.0` in the instructions.
Resolves Issue #66
=> Updated README.md to show 4.0.0-beta.2.0 version

.github/workflows/dotnet-darwin.yaml, .github/workflows/dotnet-linux.yaml, .github/workflows/dotnet-windows.yaml, Senzing.Sdk.Tests/core/RepositoryManager.cs, Senzing.Sdk.Tests/nativeszapi/InstallLocations.cs
=> update default install paths

.github/workflows/dotnet-darwin.yaml, .github/workflows/dotnet-linux.yaml, .github/workflows/dotnet-windows.yaml, README.md, Senzing.Sdk.Tests/nativeszapi/InstallLocations.cs
=> Updated InstallLocations.cs for new default location of data/support path.

Senzing.Sdk.Tests/core/SzCoreConfigManagerTest.cs, Senzing.Sdk.Tests/core/SzCoreConfigTest.cs, Senzing.Sdk.Tests/core/SzCoreEnvironmentTest.cs, Senzing.Sdk/Senzing.Sdk.csproj, Senzing.Sdk/SzConfig.cs, Senzing.Sdk/SzConfigManager.cs, Senzing.Sdk/SzEnvironment.cs, Senzing.Sdk/core/SzCoreConfig.cs, Senzing.Sdk/core/SzCoreConfigManager.cs, Senzing.Sdk/core/SzCoreEnvironment.cs
Resolves Issue #77 
Modified `SzConfig` and `SzConfigManager` interfaces as well as the "core" implementations to the new 4.0 design architecture.
=> Updated SzConfig and SzConfigManager implementations to new architecture

Senzing.Sdk.Tests/core/SzCoreEngineWhyTest.cs, Senzing.Sdk/SzEngine.cs, Senzing.Sdk/SzFlag.cs, Senzing.Sdk/SzFlagUsageGroup.cs, Senzing.Sdk/SzFlags.cs, Senzing.Sdk/core/NativeEngine.cs, Senzing.Sdk/core/NativeEngineExtern.cs, Senzing.Sdk/core/NativeFlags.cs, Senzing.Sdk/core/SzCoreEngine.cs
- Added `WhySearch()` functionality along with corresponding flag changes
- Updated unit tests accordingly
Resolves Issue #76
=> Added WhySearch functionality and corresponding flag changes

.github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/create-docfx-documentation.yaml
Issue number: senzing-factory/build-resources#179
=> senzing-factory/build-resources#179 add slack notifications

Senzing.Sdk.Demo/SzExampleExtractor.cs, Senzing.Sdk.Demo/demo/SzConfigDemo.cs, Senzing.Sdk.Demo/demo/SzConfigManagerDemo.cs, Senzing.Sdk.Tests/core/AbstractTest.cs, Senzing.Sdk/SzConfig.cs, Senzing.Sdk/SzConfigManager.cs
Adds `SzConfigDemo` and `SzConfigManagerDemo` and references to the examples in the `SzConfig` and `SzConfigManager` documentation.
=> Changes for both SzConfig and SzConfigManager examples in documentation

.vscode/cspell.json, Senzing.Sdk.Demo/demo/SzEngineDemo.cs, Senzing.Sdk.Demo/demo/SzProductDemo.cs, Senzing.Sdk/SzConfig.cs, Senzing.Sdk/SzConfigManager.cs, Senzing.Sdk/SzDiagnostic.cs, Senzing.Sdk/SzEngine.cs, Senzing.Sdk/SzEnvironment.cs, Senzing.Sdk/SzProduct.cs
Documentation examples and snippet references to `code-snippets-v4` added.
Resolves Issue #22
=> Added SzEngineDemo and example snippet include references for SzEnvironment and SzEngine

CHANGELOG.md, README.md, Senzing.Sdk/Senzing.Sdk.csproj
Updated `README.md` to reference `GlobalSuppressions.md` file.
Updated version number in `Senzing.Sdk.csproj` to version `4.0.0-beta.3.0`.
=> Updated README.md and package version to 4.0.0-beta.3.0 in Senzing.Sdk.csproj

Senzing.Sdk.Tests/SzFlagsMetaData.cs, Senzing.Sdk.Tests/SzFlagsTest.cs, Senzing.Sdk.Tests/core/SzCoreEngineWhyTest.cs, Senzing.Sdk.Tests/core/SzCoreEngineWriteTest.cs, Senzing.Sdk/SzEngine.cs, Senzing.Sdk/SzFlag.cs, Senzing.Sdk/SzFlagUsageGroup.cs, Senzing.Sdk/SzFlags.cs, index.md
Updated flags and usage groups and added meta-data flag tests
Resolves Issue #91
=> #91: Updated flags and usage groups and added meta-data flag tests

Senzing.Sdk.Demo/SzExampleExtractor.cs
=> #94: Added addtional diagnostic info to show current working directory if Senzing.Sdk.Demo checks fail

.github/workflows/dotnet-windows.yaml
=> check powershell exit codes

.github/workflows/dotnet-windows.yaml, Senzing.Sdk.Demo/SzExampleExtractor.cs
=> #96: Modified SzExampleExtractor to be more tolerant of alternate directory paths

.github/workflows/create-docfx-documentation.yaml
=> #108 run install before doc generation

.github/workflows/create-docfx-documentation.yaml
=> #108 add LD_LIBRARY_PATH for docs

.github/dependabot.yml
Issue number: senzing-factory/build-resources#195
=> senzing-factory/build-resources#195 update directories

CHANGELOG.md, Senzing.Sdk/core/SzCoreEnvironment.cs
=> #143: Updated CHANGELOG.md and changed SzCoreEnvironment.Builder constructor access level to internal

.github/workflows/create-docfx-documentation.yaml, .github/workflows/dotnet-darwin.yaml, .github/workflows/dotnet-linux.yaml, .github/workflows/dotnet-windows.yaml, .vscode/cspell.json
=> #146 4.0 updates, switch from beta to staging, test prod

Senzing.Sdk/core/SzCoreEnvironment.cs
=> #142: Updates to allow for extension of SzCoreEnvironment.Builder

Senzing.Sdk.Tests/core/SzCoreConfigTest.cs, Senzing.Sdk/core/SzCoreConfig.cs, Senzing.Sdk/core/SzCoreConfigManager.cs, Senzing.Sdk/core/SzCoreDiagnostic.cs, Senzing.Sdk/core/SzCoreEngine.cs, Senzing.Sdk/core/SzCoreEnvironment.cs, Senzing.Sdk/core/SzCoreProduct.cs
- Added SzCoreEnvironment.ValidateActiveInstance() function
- Changes SzCore* references to Native*Extern to just Native*
- Changed SzCoreConfig so it constructs with NativeConfig rather than SzCoreConfigManager
- Changed SzCoreConfig.Exporti() to fail if the environment is destroyed
- Changed SzCoreConfig.ToString() to handle exceptions from SzCoreConfig.Export()
=> Further changes for extending SzCoreEnvironment

Senzing.Sdk.Demo/demo/SzEngineDemo.cs, Senzing.Sdk/SzEngine.cs
=> #164: Updated docs and example for CountRedoRecords()
